# CI Validation

name: PowerShell Tests

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'scripts/powershell/**'

jobs:
  powershell-tests:
    name: PowerShell tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Software Report module tests
        shell: pwsh
        run: |
            $ErrorActionPreference = "Stop"
            Invoke-Pester -Output Detailed "scripts/powershell/tests"
        